typography_spectrum: 0.49165
color:
  brandColors:
    - '#103953'
    - '#2afbce'
    - '#145d6a'
    - '#1ea094'
    - '#000000'
  brandStrength: 1
  lightness: 0.4621542068198323
  saturation: 0.8535945224575698
  rhythmicContrast: 0.8139832590240985
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: jasondoesstuff
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Wandering Aimfully
description: Intentional guides for the modern traveler.
purpose: []
